-- MySQL Script generated by MySQL Workbench
-- Sun May 21 11:30:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema venta_autos_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema venta_autos_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venta_autos_DB` ;
USE `venta_autos_DB` ;

-- -----------------------------------------------------
-- Table `venta_autos_DB`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venta_autos_DB`.`USUARIO` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `venta_autos_DB`.`PRESTAMOS_BANCARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venta_autos_DB`.`PRESTAMOS_BANCARIOS` (
  `ID` INT NOT NULL,
  `nombreEmpresa` VARCHAR(45) NULL,
  `esTrabajoActual` TINYINT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `PERSONA_ID` INT NOT NULL,
  `PERSONA_Usuario_username` VARCHAR(16) NOT NULL,
  `USUARIO_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ID`, `PERSONA_ID`, `PERSONA_Usuario_username`, `USUARIO_username`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_PRESTAMOS_BANCARIOS_USUARIO1_idx` (`USUARIO_username` ASC) VISIBLE,
  CONSTRAINT `fk_PRESTAMOS_BANCARIOS_USUARIO1`
    FOREIGN KEY (`USUARIO_username`)
    REFERENCES `venta_autos_DB`.`USUARIO` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venta_autos_DB`.`ENCABEZADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venta_autos_DB`.`ENCABEZADO` (
  `ID` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(90) NULL,
  `parrafo` VARCHAR(200) NULL,
  `PERSONA_ID` INT NOT NULL,
  `PERSONA_Usuario_username` VARCHAR(16) NOT NULL,
  `USUARIO_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ID`, `PERSONA_ID`, `PERSONA_Usuario_username`, `USUARIO_username`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_ENCABEZADO_USUARIO_idx` (`USUARIO_username` ASC) VISIBLE,
  CONSTRAINT `fk_ENCABEZADO_USUARIO`
    FOREIGN KEY (`USUARIO_username`)
    REFERENCES `venta_autos_DB`.`USUARIO` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venta_autos_DB`.`AUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venta_autos_DB`.`AUTOS` (
  `ID` INT NOT NULL,
  `nombre_modelo` VARCHAR(45) NULL,
  `url_foto` VARCHAR(100) NULL,
  `anio_fabricacion` DATE NULL,
  `kilometraje` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `tipo_combustible` VARCHAR(45) NULL,
  `automatico_manual` VARCHAR(45) NULL,
  `PERSONA_ID` INT NOT NULL,
  `PERSONA_Usuario_username` VARCHAR(16) NOT NULL,
  `USUARIO_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ID`, `PERSONA_ID`, `PERSONA_Usuario_username`, `USUARIO_username`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_AUTOS_USUARIO1_idx` (`USUARIO_username` ASC) VISIBLE,
  CONSTRAINT `fk_AUTOS_USUARIO1`
    FOREIGN KEY (`USUARIO_username`)
    REFERENCES `venta_autos_DB`.`USUARIO` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venta_autos_DB`.`ACERCA_DE_venta_autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venta_autos_DB`.`ACERCA_DE_venta_autos` (
  `ID` INT NOT NULL,
  `url_foto` VARCHAR(100) NULL,
  `titulo` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(90) NULL,
  `parrafo` VARCHAR(200) NULL,
  `PERSONA_ID` INT NOT NULL,
  `PERSONA_Usuario_username` VARCHAR(16) NOT NULL,
  `USUARIO_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ID`, `PERSONA_ID`, `PERSONA_Usuario_username`, `USUARIO_username`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_ACERCA_DE_venta_autos_USUARIO1_idx` (`USUARIO_username` ASC) VISIBLE,
  CONSTRAINT `fk_ACERCA_DE_venta_autos_USUARIO1`
    FOREIGN KEY (`USUARIO_username`)
    REFERENCES `venta_autos_DB`.`USUARIO` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
